#!/bin/bash

# не понравилось
#calcurse

#ncal -y | dzen2 -p -x "2000" -y "20" -w "400" -l "28" -sa 'c' -ta 'c' -fn "xft:Monospace:pixelsize=11"\
#     -e 'onstart=uncollapse;button1=exit;button3=exit'

ncal -y > ~/tmp/popup.inf
mcview ~/tmp/popup.inf
