#!/bin/bash

PID=$(ps aux | grep CalShow | grep -v grep | awk '{print $2}')

if [[ -n $PID ]]; then
    kill $PID
    exit 0
else
    urxvtc -name CalShow -bd green -geometry 75x32 -e /home/roman/.xmonad/scripts/CalShow 
    exit 0
fi



