#!/bin/bash

#tclsh /home/roman/.xmonad/scripts/ddshow.tcl
#exit 0

PID=`ps aux | grep DfShow | grep -v grep | awk '{print $2}'`

if [[ -n $PID ]]; then
    kill $PID
    exit 0
else
    urxvtc -name DfShow -bd green -geometry 80x14 -e /home/roman/.xmonad/scripts/DfShow 
    exit 0
fi



