#!/bin/bash

PID=`ps aux | grep MemShow | grep -v grep | awk '{print $2}'`

if [[ -n $PID ]]; then
    kill $PID
    exit 0
else
    urxvtc -name MemShow -bd green -geometry 30x8 -e /home/roman/.xmonad/scripts/MemShow 
    exit 0
fi



